[logger]
level = "INFO"

[db]
type = "memorystorage"
dsn = "host=localhost port=5432 user=postgres password=postgres dbname=storage sslmode=disable"

[httpserver]
host = "localhost"
port = "8080"


# TODO
# ...
